# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QGroupBox, QLabel,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QSizePolicy, QSpinBox, QStatusBar,
    QTabWidget, QToolButton, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1132, 600)
        self.actionLight = QAction(MainWindow)
        self.actionLight.setObjectName(u"actionLight")
        self.actionDark = QAction(MainWindow)
        self.actionDark.setObjectName(u"actionDark")
        self.action_SaveSettings = QAction(MainWindow)
        self.action_SaveSettings.setObjectName(u"action_SaveSettings")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setGeometry(QRect(10, 0, 1111, 541))
        self.sensorServerTab = QWidget()
        self.sensorServerTab.setObjectName(u"sensorServerTab")
        self.loadButton = QToolButton(self.sensorServerTab)
        self.loadButton.setObjectName(u"loadButton")
        self.loadButton.setGeometry(QRect(300, 70, 23, 21))
        self.portSpinBox = QSpinBox(self.sensorServerTab)
        self.portSpinBox.setObjectName(u"portSpinBox")
        self.portSpinBox.setGeometry(QRect(370, 10, 81, 23))
        self.portSpinBox.setMaximum(65535)
        self.portSpinBox.setValue(8000)
        self.portLabel = QLabel(self.sensorServerTab)
        self.portLabel.setObjectName(u"portLabel")
        self.portLabel.setGeometry(QRect(300, 10, 53, 21))
        self.recordTimeBox = QSpinBox(self.sensorServerTab)
        self.recordTimeBox.setObjectName(u"recordTimeBox")
        self.recordTimeBox.setGeometry(QRect(370, 40, 81, 23))
        self.recordTimeBox.setMaximum(100)
        self.recordTimeBox.setSingleStep(1)
        self.recordTimeBox.setValue(10)
        self.connectButton = QPushButton(self.sensorServerTab)
        self.connectButton.setObjectName(u"connectButton")
        self.connectButton.setGeometry(QRect(10, 10, 80, 22))
        self.recordTimeLabel = QLabel(self.sensorServerTab)
        self.recordTimeLabel.setObjectName(u"recordTimeLabel")
        self.recordTimeLabel.setGeometry(QRect(300, 40, 51, 21))
        self.recordButton = QPushButton(self.sensorServerTab)
        self.recordButton.setObjectName(u"recordButton")
        self.recordButton.setGeometry(QRect(10, 40, 80, 22))
        self.onBoardRecordCheckbox = QCheckBox(self.sensorServerTab)
        self.onBoardRecordCheckbox.setObjectName(u"onBoardRecordCheckbox")
        self.onBoardRecordCheckbox.setGeometry(QRect(340, 70, 91, 20))
        self.folderEdit = QLineEdit(self.sensorServerTab)
        self.folderEdit.setObjectName(u"folderEdit")
        self.folderEdit.setGeometry(QRect(100, 70, 191, 22))
        self.activeChannelBox = QGroupBox(self.sensorServerTab)
        self.activeChannelBox.setObjectName(u"activeChannelBox")
        self.activeChannelBox.setGeometry(QRect(10, 200, 441, 91))
        self.channelBox6 = QCheckBox(self.activeChannelBox)
        self.channelBox6.setObjectName(u"channelBox6")
        self.channelBox6.setGeometry(QRect(210, 60, 91, 20))
        self.channelBox5 = QCheckBox(self.activeChannelBox)
        self.channelBox5.setObjectName(u"channelBox5")
        self.channelBox5.setGeometry(QRect(110, 60, 91, 20))
        self.channelBox3 = QCheckBox(self.activeChannelBox)
        self.channelBox3.setObjectName(u"channelBox3")
        self.channelBox3.setGeometry(QRect(310, 30, 91, 20))
        self.channelBox4 = QCheckBox(self.activeChannelBox)
        self.channelBox4.setObjectName(u"channelBox4")
        self.channelBox4.setGeometry(QRect(10, 60, 91, 20))
        self.channelBox0 = QCheckBox(self.activeChannelBox)
        self.channelBox0.setObjectName(u"channelBox0")
        self.channelBox0.setGeometry(QRect(10, 30, 91, 20))
        self.channelBox1 = QCheckBox(self.activeChannelBox)
        self.channelBox1.setObjectName(u"channelBox1")
        self.channelBox1.setGeometry(QRect(110, 30, 91, 20))
        self.channelBox7 = QCheckBox(self.activeChannelBox)
        self.channelBox7.setObjectName(u"channelBox7")
        self.channelBox7.setGeometry(QRect(310, 60, 91, 20))
        self.channelBox2 = QCheckBox(self.activeChannelBox)
        self.channelBox2.setObjectName(u"channelBox2")
        self.channelBox2.setGeometry(QRect(210, 30, 91, 20))
        self.recordNameEdit = QLineEdit(self.sensorServerTab)
        self.recordNameEdit.setObjectName(u"recordNameEdit")
        self.recordNameEdit.setGeometry(QRect(100, 40, 191, 22))
        self.workspaceLabel = QLabel(self.sensorServerTab)
        self.workspaceLabel.setObjectName(u"workspaceLabel")
        self.workspaceLabel.setGeometry(QRect(10, 70, 81, 21))
        self.ipEdit = QLineEdit(self.sensorServerTab)
        self.ipEdit.setObjectName(u"ipEdit")
        self.ipEdit.setGeometry(QRect(100, 10, 191, 22))
        self.sampleSettingsBox = QGroupBox(self.sensorServerTab)
        self.sampleSettingsBox.setObjectName(u"sampleSettingsBox")
        self.sampleSettingsBox.setGeometry(QRect(10, 100, 441, 91))
        self.sampleFrequencyLabel = QLabel(self.sampleSettingsBox)
        self.sampleFrequencyLabel.setObjectName(u"sampleFrequencyLabel")
        self.sampleFrequencyLabel.setGeometry(QRect(10, 30, 151, 21))
        self.sampleNumberLabel = QLabel(self.sampleSettingsBox)
        self.sampleNumberLabel.setObjectName(u"sampleNumberLabel")
        self.sampleNumberLabel.setGeometry(QRect(10, 60, 151, 21))
        self.sampleFrequencyBox = QSpinBox(self.sampleSettingsBox)
        self.sampleFrequencyBox.setObjectName(u"sampleFrequencyBox")
        self.sampleFrequencyBox.setGeometry(QRect(190, 30, 81, 23))
        self.sampleFrequencyBox.setMaximum(10000)
        self.sampleFrequencyBox.setValue(10000)
        self.sampleNumberBox = QSpinBox(self.sampleSettingsBox)
        self.sampleNumberBox.setObjectName(u"sampleNumberBox")
        self.sampleNumberBox.setGeometry(QRect(190, 60, 81, 23))
        self.sampleNumberBox.setMaximum(100000)
        self.sampleNumberBox.setValue(1000)
        self.verticalLayoutWidget = QWidget(self.sensorServerTab)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(460, 10, 641, 461))
        self.livePlotLayout = QVBoxLayout(self.verticalLayoutWidget)
        self.livePlotLayout.setObjectName(u"livePlotLayout")
        self.livePlotLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget.addTab(self.sensorServerTab, "")
        self.droneControlTab = QWidget()
        self.droneControlTab.setObjectName(u"droneControlTab")
        self.verticalLayoutWidget_2 = QWidget(self.droneControlTab)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(460, 10, 641, 461))
        self.dronePlotLayout = QVBoxLayout(self.verticalLayoutWidget_2)
        self.dronePlotLayout.setObjectName(u"dronePlotLayout")
        self.dronePlotLayout.setContentsMargins(0, 0, 0, 0)
        self.tabWidget.addTab(self.droneControlTab, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1132, 19))
        self.menuSettings = QMenu(self.menubar)
        self.menuSettings.setObjectName(u"menuSettings")
        self.menuTheme = QMenu(self.menuSettings)
        self.menuTheme.setObjectName(u"menuTheme")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuSettings.menuAction())
        self.menuSettings.addAction(self.menuTheme.menuAction())
        self.menuSettings.addAction(self.action_SaveSettings)
        self.menuTheme.addAction(self.actionLight)
        self.menuTheme.addAction(self.actionDark)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Drone Capture Control", None))
        self.actionLight.setText(QCoreApplication.translate("MainWindow", u"Light", None))
        self.actionDark.setText(QCoreApplication.translate("MainWindow", u"Dark", None))
        self.action_SaveSettings.setText(QCoreApplication.translate("MainWindow", u"Save Settings", None))
        self.loadButton.setText(QCoreApplication.translate("MainWindow", u"...", None))
        self.portLabel.setText(QCoreApplication.translate("MainWindow", u"Port", None))
        self.connectButton.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.recordTimeLabel.setText(QCoreApplication.translate("MainWindow", u"Time [s]", None))
        self.recordButton.setText(QCoreApplication.translate("MainWindow", u"Record", None))
        self.onBoardRecordCheckbox.setText(QCoreApplication.translate("MainWindow", u"On-Board", None))
        self.activeChannelBox.setTitle(QCoreApplication.translate("MainWindow", u"Active Channels", None))
        self.channelBox6.setText(QCoreApplication.translate("MainWindow", u"Channel 6", None))
        self.channelBox5.setText(QCoreApplication.translate("MainWindow", u"Channel 5", None))
        self.channelBox3.setText(QCoreApplication.translate("MainWindow", u"Channel 3", None))
        self.channelBox4.setText(QCoreApplication.translate("MainWindow", u"Channel 4", None))
        self.channelBox0.setText(QCoreApplication.translate("MainWindow", u"Channel 0", None))
        self.channelBox1.setText(QCoreApplication.translate("MainWindow", u"Channel 1", None))
        self.channelBox7.setText(QCoreApplication.translate("MainWindow", u"Channel 7", None))
        self.channelBox2.setText(QCoreApplication.translate("MainWindow", u"Channel 2", None))
        self.workspaceLabel.setText(QCoreApplication.translate("MainWindow", u"Workspace", None))
        self.sampleSettingsBox.setTitle(QCoreApplication.translate("MainWindow", u"Sample Settings", None))
        self.sampleFrequencyLabel.setText(QCoreApplication.translate("MainWindow", u"Sample Frequency [Hz]", None))
        self.sampleNumberLabel.setText(QCoreApplication.translate("MainWindow", u"Sample Number", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sensorServerTab), QCoreApplication.translate("MainWindow", u"Sensor Streaming/Recording", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.droneControlTab), QCoreApplication.translate("MainWindow", u"Drone Control Settings", None))
        self.menuSettings.setTitle(QCoreApplication.translate("MainWindow", u"Settings", None))
        self.menuTheme.setTitle(QCoreApplication.translate("MainWindow", u"Theme", None))
    # retranslateUi

